site_name: Packer - Plugin Xen Server

nav:
  - Welcome: index.md
  - Getting Started: getting_started.md  
  - Configuration Reference: config_ref.md
  - Examples: examples.md
  
  

theme: 
  name: readthedocs